FROM openjdk:17
#redis:
COPY ./video-auth-0.0.1-SNAPSHOT.jar /app.jar

#COPY ./video-auth-0.0.1-SNAPSHOT1.jar /app.jar
#localhost
#COPY ./video-auth-0.0.1-SNAPSHOT2.jar /app.jar
#192.168.16.2
#COPY ./video-auth-0.0.1-SNAPSHOT3.jar /app.jar
CMD ["java", "-jar", "/app.jar"]
