version: '2.2'
services:
  #  web:
  #    image: nginx:alpine
  #    ports:
  #      - "80:80"
  #    volumes:
  #      - ./html:/usr/share/nginx/html
  #    networks:
  #      - mynet
  db:
    image: postgres:11
#    networks:
#      - mynet
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"